#ifndef HARDWARE_REGISTER_DEFINITIONS_USB_REQUESTS_H
#define HARDWARE_REGISTER_DEFINITIONS_USB_REQUESTS_H

/** USBアドレスの設定 */
#define USB_REQ_SET_ADDRESS 0x05

/** デバイスディスクリプタの取得 */
#define USB_REQ_GET_DESCRIPTOR 0x06

#endif /* HARDWARE_REGISTER_DEFINITIONS_USB_REQUESTS_H */
